### ISSUE TITLE
why does 'Block automatic installation of apps' download GIMP??

### ISSUE THREAD

**Issue by robotink** [mirinsoft/debotnet#15]
the script for this downloads and installs gimp, code points to this link:
https://download.gimp.org/pub/gimp/v2.10/windows/gimp-2.10.14-setup-2.exe

why??

**Comment by Belim** [comment]
Hi,

I uploaded my local copy of the scripts in the last version 0.3.0. They contained a lot of smaller optimizations.  Unfortunately i forgot to update the script you mentioned. I tested the download function and needed a bigger file to download :) Another user @strotee mentioned this already here https://github.com/mirinsoft/debotnet/pull/10 His pull request was not applied.

Thank you for letting me know. I have updated both the package and the remote script on Git.
You can use the "Update" function or just remove the line code.
