### ISSUE TITLE
Convert to VB.Net or C#

### ISSUE THREAD

**Issue by SIRprise** [mirinsoft/debotnet#16]
Please convert or rewrite the tool from VB6 to anything using the .NET Framework to support unicode and support Paths only visible for 64bit applications.
+ It would be nice to have the sources here.

(for convert VB6->.NET see https://www.mobilize.net/solution/msdn)

**Comment by Belim** [comment]
Hi,
I've started Debotnet with C# and dropped it again. It's faster, easier and more lightweight with VB and it runs fine and smoothly. Maybe later sometime but currently there is no need for me. x64 bit would be okay but not necessary for this kind of application. Unicode support would be possible but the application remains monolingual. 
We don't need to start a discussion again how great Vb.net is, this wo find no end. In my opinion .Net is crap (except C#). 

Regards
Belim
