### ISSUE TITLE
few issues [Debotnet 0.4.0 Preview]

### ISSUE THREAD

**Issue by strotee** [mirinsoft/debotnet#17]
Version 0.4.0

1. Clicking on category on left doesn't update text (Disable Reserved Storage) in middle area. See this short [demonstration](https://i.imgur.com/UM0h7FX.mp4)
2. Similarly, text on the right side doesn't update by choosing a different category on left. One has to select text in middle in order for it to update.
3. All doesn't contain other options. It's a confusing title.
4. Security doesn't have anything?

**Comment by Belim** [comment]
Hi,

thank you. 
Some fixes has been included to the latest prev version
https://github.com/mirinsoft/debotnet/releases/tag/0.4.5

Ragards,
Belim

**Comment by strotee** [comment]
4.5 solved 1, but I'm still seeing 2 being an issue IMO.  You also added a few items to Security I see.

Regarding 2, the right text doesn't change. See this [demo ](https://i.imgur.com/GHfgPQp.mp4)to illustrate.  Also, would it be possible to display the date in user's default date format? You and I are from different continents so we look at dates differently. You show it as "25-01-2020" but here in the USA, we view it as 1/25/2020. It'd be something to consider. Thanks.

**Comment by Belim** [comment]
2, Missed it in 0.4.5, but got it now 👍 
You're right regarding the date format. Will also be fixed. Date format that corresponds to the language version will be used.

Many thanks.

**Comment by Belim** [comment]
Fix is included in latest v0.5.0
https://github.com/mirinsoft/debotnet/releases/tag/0.5.0
