### ISSUE TITLE
No more forced driver updates doesn't work [20H1]

### ISSUE THREAD

**Issue by grinch1985** [mirinsoft/debotnet#18]
![Untitled](https://user-images.githubusercontent.com/25408659/73139049-4d90b500-4072-11ea-931f-3d9d50f4c189.png)
Fresh install of windows 10 pro 20h1 with the internet unplugged, copied debotnet 0.4.5 from an usb stick to laptop, ran it, ran no more forced windows updates and no more driver updates scripts, also block automatic installation of apps script, restarted, plugged in the internet and windows started updating drivers.
![Untitled2](https://user-images.githubusercontent.com/25408659/73139082-c263ef00-4072-11ea-9237-eed56c65bd97.png)

**Comment by Belim** [comment]
Debotnet is not yet ready for 20H1. I didn't test it.

What does the query (test script function) say? Does the following key exist?
`query "HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate" /v ExcludeWUDriversInQualityUpdate`

**Comment by grinch1985** [comment]
![test drivers](https://user-images.githubusercontent.com/25408659/73141086-c26ee980-4088-11ea-88f8-e3ecea3e6333.png)
![updates test](https://user-images.githubusercontent.com/25408659/73141087-c26ee980-4088-11ea-9531-58e202adee3f.png)
it was doing the same thing on 19h2 with 0.3.0 version

**Comment by grinch1985** [comment]
![20200127_170759](https://user-images.githubusercontent.com/25408659/73186013-c1d96000-4127-11ea-98b3-ad3029a6e194.jpg)
It also happens with windows 10 version 1809

**Comment by Belim** [comment]
Please try it with latest script file. 
https://github.com/mirinsoft/debotnet/blob/master/scripts/No%20more%20forced%20driver%20updates.ds1

You can update it with internal Debotnet update function in upper right corner > Select script > Update

**Comment by grinch1985** [comment]
I ve managed to get it done with Stopwinupdates 2.5, when i ll install windows again i ll give it a try
