### ISSUE TITLE
create system restore points before executing actions...

### ISSUE THREAD

**Issue by raykai** [Mirinsoft/Debotnet#2]
plz add this task of auto-create a system restore points before executing actions in the program so if something happens we can role back

**Comment by iMirin** [comment]
Hi raykai,

I will do :) ...in the upcoming beta release (maybe today).
For the first I will provide a script (will be shipped per default) and simple command for creating system restoration points.

The stable release should also bring a function to backup e.g. registry keys, before executing a script.

Merry Christmas
Belim

**Comment by iMirin** [comment]
Check this release out!
https://github.com/Mirinsoft/Debotnet/releases/tag/0.1.4
