### ISSUE TITLE
Cortana

### ISSUE THREAD

**Issue by JasmineRuca** [mirinsoft/debotnet#20]
**Latest ver of Debotnet isn't removing Cortana. Windows 10 Home, Build 18362.19h1_release.190318-1202. (all up to date).

Other than that, Debotnet seems to be working flawlessly.**

**Comment by Belim** [comment]
Hi Jasmine,

thanks for the positive feedback. 
Regarding Cortana unfortunately I have no experience yet on Win 10, Home. The script is based upon third party files and the install_wim_tweak.exe from https://msfn.org/board/topic/152688-win6x_registry_tweak/
I've included it in v0.4.5 preview. Perhaps, there is something that I may learn.

Regards
Belim
