### ISSUE TITLE
Actually check current state of tweaks on the system

### ISSUE THREAD

**Issue by ltGuillaume** [mirinsoft/debotnet#21]
From the looks of it, it seems like Debotnet only locally saves the state of the applied tweaks in the INI-file, instead of actually checking the state of them on the system. This causes two issues:

1) Tweaks that have been reset by the system are still shown as if they were applied inside Debotnet
2) Tweaks that have been applied by using other programs, .reg-files or other means are not detected as being applied by Debotnet.

This (especially 1) would severely debilitate Debotnet's usefulness, as you'll never really know if tweaks are still applied; you can only see whether the tweaks _have been applied in the past_, not whether they're actually still active. Similarly, when you copy the program to an USB stick and try to deploy it on another system, I think it'll show as if the tweaks you applied before on a different system are _allready_ applied on the new system.

**Comment by Belim** [comment]
Hi ltGuillaume ,

nothing is stored locally (here in the script files that are actually built like .INI-files). 
These files contain the code, which is going to be executed. You can consider Debotnet as interpreter for cmd, powershell code (which is defined in these script files)

But i know what you mean and a status query (in the form of on/off switches) of already executed code or applied tweaks is not possible. I follow a different concept here. It is simple as executing PowerShell code. Once done, you can also go back with Debotnet in most cases by running an "Undo".  You can also get a query anytime by running a "Test" of already applied settings and compare them maybe to actual code.

I hope this clarifies things

Kind regards from Germany
Belim
