### ISSUE TITLE
Preservation of script selections

### ISSUE THREAD

**Issue by xypha** [mirinsoft/debotnet#24]
Feature request/improvement
Disable the preservation of script selections when the program is closed and opened, or provide the option in settings to preserve/discard script selections made in previous run

**Comment by Belim** [comment]
Hmm, unsure about this. An option to start always fresh ... What is the purpose?

As workaround you could export a blank profile and put an "/custom" cli switch on Debotnet, which would be imported on startup
https://github.com/mirinsoft/debotnet/wiki/Command-line
