### ISSUE TITLE
broken start menu search bar

### ISSUE THREAD

**Issue by ppolewicz** [mirinsoft/debotnet#27]
Today I've run a bunch of scripts, one of them to disable web search in start menu, but now my start menu search is broken completely, so if I hit win key and write "note", nothing appears.

How can I fix it?

**Comment by Belim** [comment]
This should not be possible. ONLY this value is twisted 
 "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" /v ConnectedSearchUseWeb /t REG_DWORD /d 1 /f

To revert the changes.
Select "Disable web search in Start menu" > Undo script

**Comment by Belim** [comment]
It's a global Microsoft bug!
The search in Windows 10 is dependent on Bing. If there are problems there, you can no longer use the search. Unfortunately this shows how Microsoft has programmed the search. There is nothing local. It all goes through the server. 

https://www.windowscentral.com/windows-search-down-many-showing-blank-box-instead-search-results

**Comment by ppolewicz** [comment]
I am speechless.

Thank you @Belim for your help.
