### ISSUE TITLE
How to revert disables?

### ISSUE THREAD

**Issue by ppolewicz** [mirinsoft/debotnet#28]
In case I ever want Cortana (or some other feature) back, how can I bring it back? Is there an option in the program to do it, or do I need to reinstall the system?

**Comment by Belim** [comment]
If you removed it by running the script "Remove Cortana" it will not be possible.

When you select the script, there should be a warning message telling you that you do so at your own risk. Cortana is very sensitive till Win 10, version 19H2 and shout NOT be uninstalled. This is also not recommended by Debotnet
