### ISSUE TITLE
[request] Uninstall UWP apps for all users

### ISSUE THREAD

**Issue by dryoma** [mirinsoft/debotnet#29]
Hey there, 
First of all, thanks for working on such a great tool and having it open-source! 

A feature request: would be nice to be able to remove UWP apps not just for the current user, but for all users. Would be really nice to do the debloating just once instead of for every new/existing user.

**Comment by Belim** [comment]
Hi,

glad you enjoyed it 💯 
To achieve this you would have only to put the -allusers parameter on each bloatware script

OLD
`File1=Run,powershell -command "Get-AppxPackage *Microsoft.3dbuilder* | Remove-AppxPackage"`
**NEW**
`File1=Run,powershell -command "Get-appxpackage -Allusers *CommsPhone* | Remove-AppxPackage -AllUsers",STDOUT`

I'm not in favor shipping this per default .

**Comment by dryoma** [comment]
Fair enough. And how about an option for this? Some users might not be confident enough for manually editing scripts, plus the changes would be discarded after updating the program.

**Comment by Feky** [comment]
I want this!

**Comment by Belim** [comment]
I've opened a new Download section for getting custom script packages for Debotnet

**Debotnet Packs**
[https://www.mirinsoft.com/debotnet-packs](url)

You will find here also a package for removing apps from all user accounts.
