### ISSUE TITLE
CLI / config setup

### ISSUE THREAD

**Issue by fam4r** [mirinsoft/debotnet#3]
Hello,

nice work!

Can it be used via CLI in order to be automatized (eg. post-installation automatic setup) and/or does it use a config file to be just ready with pre-built configuration (enabled/disabled scripts)?

Thanks

**Comment by iMirin** [comment]
Hi fam4r,

thank you for the nice words :P
This is currently not possible, but CLI support is in the pipeline and will be integrated in one of the upcoming version (maybe after the stable). 

Kind regards
Belim

**Comment by iMirin** [comment]
Hi again,

CLI support is included :) Take a look at the latest release.
https://github.com/mirinsoft/debotnet/releases/tag/0.2.5

Regards
