### ISSUE TITLE
Feat.req. make option to run app with admin rights by default?

### ISSUE THREAD

**Issue by necros2k7** [mirinsoft/debotnet#30]
subj

**Comment by Belim** [comment]
Yes, there is room for improvement here.
I'm not sure whether to add an option to start always with elevated permissions or to check the new "RequireAdmin" parameter in the Info Header of the script files and to recommend starting with higher rights.

**Comment by Belim** [comment]
Option to run always with elevated rights has been added to release 0.6.0
https://github.com/mirinsoft/debotnet/releases/tag/0.6.0

Some other improvements will be made in upcoming versions.
