### ISSUE TITLE
Feat.req. make some template-kind system with user checked scripts

### ISSUE THREAD

**Issue by necros2k7** [mirinsoft/debotnet#31]
Like a button in app interface for user to name ex. Notebook , Tablet, Desktop - and each "button" after pressing should run user selected scripts, 1 by 1. So after new OS install/ reinstall all user have to do is run app and press corresponding button to "debotnet" it`s system.

**Comment by Belim** [comment]
What about running Debotnet in command-line?
https://github.com/mirinsoft/debotnet/wiki/Command-line
