### ISSUE TITLE
Removing reference to wscsvc causes issues if you still have Windows Defender

### ISSUE THREAD

**Issue by jlagden** [mirinsoft/debotnet#34]
The first line of Federico Dossena's script Remove Telemetry (Advanced) removes the registry key for Windows Security Center Service (But doesn't actually remove it) this breaks Windows Defender (even if you don't have any Windows Defender options selected)

Suggest this registry change is moved to another section

**Comment by Belim** [comment]
Thank you very much for this Info. Really appreciated.
Didn't know that. I run it several times on my VM and nothing wrong happens and Defender did not break.

Following line will be removed from the script in the next nightly and also stable release.
`File18=Run,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "wscsvc" ^| find /i "wscsvc"') do (reg delete %I /f)`

**Comment by Belim** [comment]
Fixed in release 0.6.3
https://github.com/mirinsoft/debotnet/releases/tag/0.6.3
