### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by msakallah** [mirinsoft/debotnet#36]
Running the scripts like the CleanMgr+, Geek, Manage Windows updates and Patch Windows apps seem to fail downloading after running a lot of the recommended scripts under Privacy, and Start. 

I did a clean format of my machine, and ran dbotnet and did 3 things. Recommended Start, Recommended Privacy, and Recommended Update in the tool. and haven't been able to download anything within dbotnet. however I can copy and paste the URLs and download them manually.

**Comment by Belim** [comment]
1. Make sure that wget.exe is located in bin folder of Debotnet
2. You have moved the Debotnet package from one location to another. In this case the UserProfile has changed and the path to wget.exe 
Check debotnet-settings.txt file in bin folder of Debotnet
`[Wget]
OutputDir=C:\Users\%Username%\Desktop\Debotnet
WgetPath=C:\Users\%Username%\Desktop\Debotnet\bin\wget.exe`

The paths are correct?

3. If you want to skip above steps, the easiest thing to do would be to reset the app configuration by deleting debotnet-settings.txt file in bin folder of Debotnet
