### ISSUE TITLE
error when removing game bar

### ISSUE THREAD

**Issue by mrjgriffin413522** [mirinsoft/debotnet#37]
under the category bloatware when you select gamebar it only removes the "xboxgamingoverlay" which no longer actually removes the game bar. you can still see the xbox game bar is present when you go to your installed apps.

**Comment by Belim** [comment]
The Xbox app should remove the Xbox GameBar
Goto `bloatware > XBox` and run it ;)

**Comment by Belim** [comment]
As I see this you are right. 

Please replace the Code section in `bloatware > Gamebar`

from
`File1=Run,powershell -command "Get-AppxPackage *Microsoft.XboxGameOverlay* | Remove-AppxPackage""`

**TO**
`File2=Run,powershell -command "Get-appxpackage -allusers *Microsoft.XboxGamingOverlay* | Remove-AppxPackage"`

This worked on for me ver 1909, Build 18363.657

**Comment by Belim** [comment]
Please replace the Code section in bloatware > Gamebar

from
`File1=Run,powershell -command "Get-AppxPackage *Microsoft.XboxGameOverlay* | Remove-AppxPackage"`

TO
`File2=Run,powershell -command "Get-appxpackage *Microsoft.XboxGamingOverlay* | Remove-AppxPackage"`

This worked for me ver 1909, Build 18363.657

**Comment by Belim** [comment]
Fix is included to release 0.6.5
https://github.com/mirinsoft/debotnet/releases/tag/0.6.5
