### ISSUE TITLE
Improvement: Start debotnet with pre defined settings from a powershell script to automate things

### ISSUE THREAD

**Issue by stevleibelt** [mirinsoft/debotnet#41]
Hey Mirinsoft,

I am really thankful for your work and hope you get enough donations for your great work.
Since I start to have a kind of same and same task again, I started writing a basic powershell script to check if my finest selection of default software is installed or not.
Now, as another evolution, I would like to implement to automate "my best guesses"-settings when I use debotnet.

So right now, I start debotnet by hand and click on the areas to get my preselected settings plus hit "run".
I would like to automatically execute my sections with my settings from the command line via my powershell script.
I found the [command line](https://github.com/mirinsoft/debotnet/wiki/Command-line) section in the wiki but I don't have a clue how to use it.
I also found my local `debotnet-settings.txt` and with that I am irritated how I have to convert this txt file into the script file mentioned in the wiki.

Can you please push me into the right direction, if you get my question :).

Best regards,
Stev

**Comment by Belim** [comment]
Hi Stev,

of course this is possible. Therefore we have the command-line support.

1. Select all script files you wish to execute all at one go
2. Goto Import > Export profile > Enter a filename (your previously enabled scripts will be saved to this .SCRIPT file)
3. Create a shortcut of Debotnet.exe and add the `/auto`
 paramter after `C:\Users\YOUR USERNAME\Desktop\Debotnet\Debotnet.exe`

So it will look like this
`C:\Users\YOUR USERNAME\Desktop\Debotnet\Debotnet.exe /auto`

You can optionally use `Start-Process` with the EXE if you want to capture a reference to the executable to gain more control over it from Powershell.

It would look something like this
`Start-Process -FilePath C:\Users\YOUR USERNAME\Desktop\Debotnet\Debotnet.exe /auto`

Regards from Germany
Belim

**Comment by Belim** [comment]
You can also run predefined script files by exporting them to a `.SCRIPT ` file.

1. Select all script files you wish to execute all at one go
2. Goto Import > Export profile > Enter a filename (your previously enabled scripts will be saved to this .SCRIPT file)
3. Create a shortcut of Debotnet.exe and add refrence to previously saved .SCRIPT file in your command-line parameter.

It will look something like this
C:\Users\YOUR USERNAME\Desktop\Debotnet\Debotnet.exe %UserProfile%\Desktop\MY-SCRIPT-FILE.SCRIPT

**Comment by stevleibelt** [comment]
Thank you very much for your quick and detailed response @Belim!
