### ISSUE TITLE
Debotnet.exe (0.7.5) is detected as "PDM:Trojan.Win32.Generic" from Kaspersky Endpoint Security

### ISSUE THREAD

**Issue by stevleibelt** [mirinsoft/debotnet#44]
Hey,

Starting with version 0.7.5, our Kaspersky Endpoint Security is detecting Debotnet.exe as `PDM:Trojan.Win32.Generic".

Sadly, that is currently all I know so far.
Does anyone else have issues with this too?
Until this issue is solved, I switch back to Debotnet.exe 0.7.

**Comment by Belim** [comment]
Hi stev,

please read the notice on the latest blog entry
[https://www.mirinsoft.com/blog/18-debotnet/18-debotnet-0-7-5-adds-support-for-debloat-windows-10-project](https://www.mirinsoft.com/blog/18-debotnet/18-debotnet-0-7-5-adds-support-for-debloat-windows-10-project)

> If you encounter messages from your AV (Bitdefender, GData, Emisoft) flagging Debotnet.exe as Virus/Trojan, please note that all these are FALSE POSITIVES. Bitdefender share their definitions with other AV vendors (such as Emisoft, GData etc.) and all are reporting the same results. Bitdefender updated their engine and since three weeks I can not control these false positives, except reporting them to their Labs. Usually the detection is removed up to 24 hours. 

**It's 101% a false positive.**
On VirtusTotal the detection is updated and it's also clean from Kaspersky as you can see here
[https://www.virustotal.com/gui/file/b5c41a37e929669b0ba2b2a68f6c211f34d54df6c69c022c53cf8ee427170f11/detection](https://www.virustotal.com/gui/file/b5c41a37e929669b0ba2b2a68f6c211f34d54df6c69c022c53cf8ee427170f11/detection)

You should maybe update your definitions manually.
