### ISSUE TITLE
People selection in Bloatware doesn't remove People App

### ISSUE THREAD

**Issue by jlagden** [mirinsoft/debotnet#45]
Hi,

I've noticed the People App did not get removed despite me selecting it.
I have removed the People App manually using powershell (just the people package not People Experience) and it seems ok so far

This is with Windows 10 1909 (Just did a fresh install)

**Comment by Belim** [comment]
Hi,

yes, will be fixed with upcoming release and updated packages.

The code should be

`[Code]
File1=Run,powershell -command "Get-AppxPackage *people* | Remove-AppxPackage"`
