### ISSUE TITLE
Remnants of One Drive still on system

### ISSUE THREAD

**Issue by jlagden** [mirinsoft/debotnet#46]
Hi,

Not sure if this is a bug or not or whether anything can be done about it, I selected "Disable OneDrive Everywhere"

However there are still some remnants of One Drive left over:

- One Drive still in Start Menu, clicking on it opens empty window which does nothing
- One still in applications list, trying to uninstall gives error message saying it can't find the onedrivesetup.exe

**Comment by Belim** [comment]
Have you uninstalled OneDrive before running the script? It is recommend to uninstall it the normal way and running afterwards the script to remove all remnants.

**Comment by Belim** [comment]
Please try to remove the remnants with the new scripts provided by W4RH4WK / Debloat-Windows-10

It can be also found in `Debotnet > debloat windows 10 > 4. Remove OneDrive`
