### ISSUE TITLE
"Remove GameBar features" - Issue

### ISSUE THREAD

**Issue by ROvidiu18** [mirinsoft/debotnet#47]
Remove GameBar script actually toggles ON the recording features of Game Bar in PC Settings.

**Comment by Belim** [comment]
Which script do you mean exactly? Can you show me the part that activates it?

**Comment by ROvidiu18** [comment]
![image](https://user-images.githubusercontent.com/60251887/78568282-8a271c80-782a-11ea-880d-9b51161f567e.png)

Here is a screenshot with the script I am talking about and it's code.

**Comment by ROvidiu18** [comment]
![image](https://user-images.githubusercontent.com/60251887/78569566-7977a600-782c-11ea-9b32-0661d606e647.png)

And this is what I mean by saying that it 

> toggles ON the recording features of Game Bar in PC Settings

**Comment by Belim** [comment]
You're right. The Datatype was set to **REG_SZ** in `HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR" /v AllowgameDVR /t REG_SZ`

It should be an **REG_DWORD**
`HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR" /v AllowgameDVR /t REG_DWORD`

I've added also some other optimizations.
Please update your script file via Debotnet > Update

Thanks again for reporting.
Belim
