### ISSUE TITLE
there is no way to change the encoding or font

### ISSUE THREAD

**Issue by gema-arta** [mirinsoft/debotnet#48]
the results are unreadable if the system locale differs from the english one

**Comment by gema-arta** [comment]
![2020-04-05 23_00_57-Debotnet](https://user-images.githubusercontent.com/4130081/78509235-682f8a80-7795-11ea-9eed-f126b663b10a.png)

**Comment by Belim** [comment]
There is no no need for changing font and encoding as locale dependent messages thrown by the cmd.exe are used. The strings refer to %WinDir%\System32\en-US\cmd.exe.mui

I use it in german as well as english and have seen it also in korean and polish.

Something must be wrong with the codepage on your system? Which system locale is it? Please try also on a second machine.

**Comment by stevleibelt** [comment]
@gema-arta I can confirm that debotnet is working find on multiple english and german based windows 10 systems. No strange or wrong encoded fonts seen by me since weeks.
