### ISSUE TITLE
Misspelling 

### ISSUE THREAD

**Issue by strotee** [mirinsoft/debotnet#5]
There is a misspelling on the most current version (0.2.9).  "Turn off Windows udates sharing", should be "Turn off Windows updates sharing". It appears that you're missing the letter P in updates. It's also wrong on the hover over text as well. I haven't noticed any other misspellings though I haven't combed over  everything. Thank you.

https://i.imgur.com/01QBBjZ.png

**Comment by Belim** [comment]
Hi,

thanks for pointing this out to me. I would never have seen that 🤣 
Will be fixed in upcoming release. It's already updated in repo @https://github.com/mirinsoft/debotnet/tree/master/scripts

Regards
Belim

**Comment by strotee** [comment]
Do you want me to open another issue for a typo I found in \scripts\all\Remove Xbox Game Speech Window.ds1?

Line 12: File1=Run,owershell -command "Get-AppxPackage *Microsoft.XboxSpeechToTextOverlay* | Remove-AppxPackage"

Should be “Run,powershell…”

**Comment by Belim** [comment]
@strotee 
Great, thanks again. 
Script has been updated https://github.com/mirinsoft/debotnet/edit/master/scripts/Remove Xbox Game Speech Window.ds1

**Comment by strotee** [comment]
Looks better, thanks.
