### ISSUE TITLE
Enhancement - Add option to disable hibernate to "Slim" section.

### ISSUE THREAD

**Issue by BuzzPCSOS** [mirinsoft/debotnet#50]
First congratulations on the exciting Windows privacy and tweaking tool.
Could there be an option to disable the hibernate function for those who rarely use the feature. Disabling it can free up quite a bit of space depending on how much ram you have. If you are using an SSD turning off the hibernate function can improve SSD longevity.
I roughed out a script that seems to work;
[Code]
File1=Run,powershell.exe -command powercfg.exe /hibernate off
[Undo]
File1=Run,powershell.exe -command powercfg.exe /hibernate on

**Comment by BuzzPCSOS** [comment]
[Info]
ID=Disable Hibernate
Ver=1.0
Desc=If you’re looking to free up space on your disk, you can disable the hibernate function if you rarely use the feature. In fact, if you are using a SSD for your Windows 10 computer, it’s better to turn off the hibernate function to save SSD life.
Dev=Buzz.PC.SOS
DevURL=
WinVer=Compatible with Windows 10
Evaluation=Custom
EvaluationColor=562765

[Code]
File1=Run,powershell.exe -command powercfg.exe /hibernate off


[Undo]
File1=Run,powershell.exe -command powercfg.exe /hibernate on

**Comment by Belim** [comment]
Many thanks :)
I've uploaded your script to the Debotnet packs section.
https://www.mirinsoft.com/debotnet-packs/download/12-debotnet-packs/23-debotnet-script-disable-hibernate
