### ISSUE TITLE
Enhancement - Add option to lower user account control level (UAC).

### ISSUE THREAD

**Issue by BuzzPCSOS** [mirinsoft/debotnet#51]
Could there be an option to reduce the UAC level to the lowest level.
Although this is not a privacy tweak it does make the using Windows a lot easier and is usually my first tweak when working on a new PC.
I have included a working script that I use although I am sure that it could be improved upon as there is no undo.

**Comment by BuzzPCSOS** [comment]
[Info]
ID=Lower UAC level
Ver=1.0
Desc=Lower UAC level (disabling it completely would break apps)
Dev=Buzz.PC.SOS
DevURL=
WinVer=Compatible with Windows 10
Evaluation=Custom
EvaluationColor=562765

[Code]
Task1=Try,query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v ConsentPromptBehaviorAdmin,STDOUT
Task2=Try,query "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v PromptOnSecureDesktop,STDOUT
File1=Reg,add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 0 /f,STDOUT
File2=Reg,add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v PromptOnSecureDesktop /t REG_DWORD /d 0 /f,STDOUT

**Comment by Belim** [comment]
I will test it soon and add it to the Debotnet packs section.

Did you try my new app **PimpApp**
https://github.com/mirinsoft/pimpapp

The scripting engine is completely based on PowerShell and such tasks could be implemented easier.

**Comment by BuzzPCSOS** [comment]
I have been following the new app with interest and will have to look at the way script it written for it. Debotnet was simply the first one on the scene and had all the features and expandability that I was looking for. Previously the Windows 10 Initial Setup script, also on GitHub, was my go-to tweaking script but I prefer the convenience of check boxes and the option to read a script description before choosing it.
Keep up the good work.

Buzz

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Belim** [comment]
With PimpApp e.g., you can already cover with the beginners template - it's one simple PowerShell script - the whole privacy rules located in Debotnet's **start** section.
It is simpler but also more powerful

**You could disable UAC with this one-liner**
`Set-ItemProperty -Path HKLM:\Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -Value 0`

**or enable it**
`Set-ItemProperty -Path HKLM:\Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -Value 1`

Btw, do you like the name PimpApp ? some beg me to change it and others love it :D

**Comment by BuzzPCSOS** [comment]
I have just voted on wether your app needs to be renamed. Makes me think of Huggy Bear from Starsky and Hutch, and for some reason his car. Probably a series long before your time 😃
I will take a closer look at using PimpApp to directly run PowerShell scripts. I must admit that I rather like the way Debotnet works and being able to keep a single file for each instruction. It made updating and adding custom scripts much easier than maintaining a big scripts with everything in them.
I wonder if Debotnet could be persuaded to directly run PowerShell scripts ?
Best regards
Buzz

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Belim** [comment]
Oh noo, another PimpApp hater :(
You can run in Debotnet simple one/two-liner scripts written in powershell. It cant capture complex script files of powershell as it uses for redirection the cmd.exe I will not "pimp" ;) the scripting engine in Debotnet and as this could be a very complex task. I will focus more on "PimpApp" (what the voting results look like now a new name must be found) and eventually Debotnet may even be discontinued.

Starsky and hutch is little over 10 years ahead of me and I've heard about it before but never about Huggy Bear :O
