### ISSUE TITLE
Disable telemetry script (start->disable telemetry)

### ISSUE THREAD

**Issue by ombrisban** [mirinsoft/debotnet#52]
Hi,

In the script, where it say:
net stop dmwappushsvc
"HKLM\SYSTEM\ControlSet001\Services\dmwappushsvc"
"HKLM\SYSTEM\ControlSet001\Services\DiagTrack"

I think it should say:
net stop dmwappushservice
"HKLM\SYSTEM\CurrentControlSet\Services\dmwappushservice"
"HKLM\SYSTEM\CurrentControlSet\Services\DiagTrack"

Thanks a lot for your work.

**Comment by Belim** [comment]
Can not confirm this. It shoud be right as it is.
