### ISSUE TITLE
SQL Server Management Studio no telemetry

### ISSUE THREAD

**Issue by natvasen** [mirinsoft/debotnet#53]
Hi Belim,

Would you add an option/script to disable telemetry in Microsoft SSMS?
According to: https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-telemetry-ssms

Something as simple as this should be enough:

﻿# Disable SSMS telemetry feedback

$path17 = 'HKCU:\Software\Microsoft\SQL Server Management Studio\14.0'
$path18 = 'HKCU:\Software\Microsoft\SQL Server Management Studio\18.0_IsoShell'
$entry = 'UserFeedbackOptIn'

Set-ItemProperty -Path $path17 -Name $entry -value 0

Regards

**Comment by Belim** [comment]
Hi,
this is tricky in Debotnet, but it's possible with the successor tool called SharpApp
https://github.com/mirinsoft/sharpapp
