### ISSUE TITLE
Question: Is debotnet dead now in favor of SharpApp?

### ISSUE THREAD

**Issue by stevleibelt** [mirinsoft/debotnet#54]
Hey @Belim,

as the subject is asking it already.
Will debotnet stay in the current state to became replaced by [SharpApp](https://github.com/mirinsoft/sharpapp)?

On the SharpApp issue board, I found [a question](https://github.com/mirinsoft/sharpapp/issues/16) asking the same but from a different side.
What are the big differences between debotnet and sharpapp?
If the truth is that you've figured out that the core setup of debotnet is not fitting and you fixed that in sharpapp, I am fine with this answer.

It would also be good to know if sharpapp will be the successor of debotnet meaning debotnet won't get any fixed or features in the future.

Best regards and thanks for your work,
Stev

**Comment by Belim** [comment]
Hi Stev,

i will comment on that in the blog soon. 
But it is indeed so. I have decided to stop the development on Debotnet and focus completely on SharpApp as successor. Debotnet will not get updated script files for the upcoming Windows 10 versions, 20H1 and 20H2.

Debotnet is compiled with Visual Basic and I have reached my limits with the planned implementations (e.g. integration of PowerShell scripting), so I discard the development language. SharpApp was written from scratch in C# and the development it's a lot easier (both from the user and the developer side). 80% of Debotnet script files have already been migrated to SharpApp (as new PowerShell templates).

The main advantage of SharpApp is that scripting is solved with PowerShell (every admin knows it or should at least and every Windows 10 user has it on the system whether he wants to or not).

SharpApp is also working with "all-in-one" PowerShell script files. I call them "Templates". There will be for every scenario a template file (e.g. Beginner, Advanced) and you can run them in a flush not like Debotnet and other consorts where you have to go through a thousand options and checkboxes.  This makes the "purification" of Windows 10 after a fresh installation much easier.

Hope you will also remain a customer of SharpApp :smiley:

Regards,
Belim

**Comment by stevleibelt** [comment]
Hey @Belim,

thank you for your quick reply.
Nice my thoughts where going into the right direction. I can understand that things became complicated.
Restarting from scratch with c# is a great idea plus a good knowledge aggregator learning c#.
If you ever plan to open source your c# code, plan to build a testing pipeline etc. pp. just give me a wave. I am interested in and really liked your debotnet much.

Cheers,
Stev

**Comment by Belim** [comment]
At least I will never let it die like Debotnet. But it had to happen. Things change and they have for a long time. I am also not completely closed to the open source idea

**Comment by stevleibelt** [comment]
@Belim Thank you very much making Debotnet Open Source while replacing it with other solutions.

That is a great way to "let things go" and giver others a chance to learn or to improve.

Please keep up with your good work!

**Comment by Belim** [comment]
@stevleibelt It's on you to make a Debotnet 2.0 :smiley:
